### ISSUE TITLE
add a USB connection daughtercard design

### ISSUE THREAD

**Issue by herrold** [hulkco/The-Key#1]
would it be possible to add a USB connection, and optional FTDI circuitry, to the 'back' side of the design

to permit plugging it directly (though the daughtercard) into a computer for interaction with the computer, as well as for flashing images in

**Comment by hulkco** [comment]
Hello Herrold, I'm just thinking about which USB chip to use, if the CP2102 or the FT230XS, I think I'll use the FT230XS, since it's easier to weld, I'll see if it's possible to keep the size of the card, or I'll have to do it a bit larger, I do not want to use components smaller than 0805, in a few days it will be available in this same repository.
Both versions will be preserved.
regards
